# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='T\xedtulo')),
                ('body', models.TextField(verbose_name='Texto')),
                ('created_time', models.DateTimeField(verbose_name='Data de Cria\xe7\xe3o')),
                ('last_modified_time', models.DateTimeField(verbose_name='\xdaltima modifica\xe7\xe3o')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1)),
                ('abstract', models.CharField(blank=True, max_length=54, null=True, verbose_name='Resumo')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('topped', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Usu\xe1rio')),
                ('user_email', models.EmailField(max_length=255, verbose_name='Email')),
                ('body', models.TextField(verbose_name='Texto')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoal.Article', verbose_name='Artigo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='\xdaltima Modifica\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descri\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='\xdaltima Modifica\xe7\xe3o')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoal.Category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pessoal.Tag'),
        ),
    ]
